name: Build Docker images

on:
  # Run every other morning, time chosen arbitrarily as a likely low-activity period.
  # This will ensure that the images are up to date with releases on their base images.
  schedule:
    - cron:  '40 11 * * */2'
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8

jobs:

  cups:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push cups Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: cups
          file: cups/Dockerfile
          tags: florianpiesche/cups-arm:latest
          platforms: ${{ env.PLATFORMS }}
          push: true

  mailpile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push mailpile Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: mailpile
          file: mailpile/Dockerfile
          tags: florianpiesche/mailpile-arm:latest
          platforms: ${{ env.PLATFORMS }}
          push: true

  sane:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sane Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: sane
          file: sane/Dockerfile
          tags: florianpiesche/saned-arm:latest
          platforms: ${{ env.PLATFORMS }}
          push: true

  sftp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push sftp Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: sftp
          file: sftp/Dockerfile
          tags: florianpiesche/sftp-arm:latest
          platforms: ${{ env.PLATFORMS }}
          push: true

  transmission:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push transmission Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: transmission
          file: transmission/Dockerfile.transmission
          tags: florianpiesche/transmission-arm:latest
          platforms: ${{ env.PLATFORMS }}
          push: true

  transmission-rss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push transmission-rss Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: transmission
          file: transmission/Dockerfile.transmission-rss
          tags: florianpiesche/transmission-rss-arm:latest
          platforms: ${{ env.PLATFORMS }}
          push: true
