name: Build simple Docker images

on:
  # Run every other morning, time chosen arbitrarily as a likely low-activity period.
  # This will ensure that the images are up to date with releases on their base images.
  schedule:
    - cron:  '40 11 * * */2'
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8
  ARMV6_ONLY: swarmpit-agent

jobs:

  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE: ['cups', 'mailpile', 'sane', 'sftp', 'swarmpit-agent',
                'transmission', 'transmission-rss']

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.IMAGE }} armv6 Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: ${{ matrix.IMAGE }}
          file: ${{ matrix.IMAGE }}/Dockerfile
          tags: florianpiesche/${{ matrix.IMAGE }}-arm:armv6
          platforms: linux/arm/v6
          push: true
  
      - name: Build and push ${{ matrix.IMAGE }} Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: ${{ matrix.IMAGE }}
          file: ${{ matrix.IMAGE }}/Dockerfile
          tags: florianpiesche/${{ matrix.IMAGE }}-arm:latest
          platforms: ${{ env.PLATFORMS }}
          push: true
        if: contains(${{ env.ARMV6_ONLY }}, ${{ matrix.IMAGE }}) == false

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: florianpiesche/${{ matrix.IMAGE }}-arm
          readme-filepath: ${{ matrix.IMAGE }}/README.md