name: Build MariaDB ARM Docker images

on:
  # Run every other morning, time chosen arbitrarily as a likely low-activity period.
  # This will ensure that the images are up to date with releases on their base images.
  schedule:
    - cron:  '40 11 * * */2'
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this workflow.
  push:
    branches:
      - main
    paths:
      - .github/workflows/mariadb.yml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/mariadb.yml

jobs:
  mariadb:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        VERSION: ["10.1", "10.2", "10.3", "10.4", "10.5"]
    steps:
      - name: Get MariaDB Docker Libary repo
        uses: actions/checkout@v2
        with:
          repository: docker-library/mariadb

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push mariadb ARM Docker image
        uses: docker/build-push-action@v2.1.0
        with:
          context: ${{ matrix.VERSION }}
          tags: florianpiesche/mariadb-arm:${{ matrix.VERSION }}
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64/v8
          push: true
